#!/usr/bin/env python3
"""Generate Beamer score slides for every JSON file in scraped-json."""

import datetime
import getpass
import hashlib
import json
import platform
import re
import sys
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parent
INPUT = ROOT / "scraped-json"
OUTPUT = ROOT / "beamer-slides"
ACCOUNT_RE = re.compile(r"(?<!\d)\d+(?:\.\d+){2,}(?!\d)")
TEX_CHARS = {"\\": r"\textbackslash{}", "{": r"\{", "}": r"\}",
             "#": r"\#", "$": r"\$", "%": r"\%", "&": r"\&",
             "_": r"\_", "^": r"\textasciicircum{}", "~": r"\textasciitilde{}"}


def tex(value):
    """Normalize whitespace and escape TeX syntax without changing words."""
    value = " ".join(str(value or "").split())
    return "".join(TEX_CHARS.get(character, character) for character in value)


def overall_text(value):
    """Keep the original wording, starting numbered responses 2 and 3 anew."""
    parts = re.split(r"(?m)^\s*(?=[23]\.\s)", str(value or ""))
    return r"\par\vspace{0.5em}".join(tex(part) for part in parts if part.strip())


def score_node(row, score):
    positions = {-1: (0, r"\rd{$\blacktriangle$}"),
                  0: (1, r"$\blacktriangle$"),
                  1: (2, r"\bl{$\blacktriangle$}")}
    if score not in positions:
        raise ValueError(f"c{row}: unsupported score {score!r}; expected -1, 0, or 1")
    x, symbol = positions[score]
    return f"    \\node at ({x},-{row + 1}) {{{symbol}}};"


def make_slides(document, path, output_name=None):
    metadata = document["metadata"]
    data = document["data"]
    areas = data["areas"]
    if len(areas) < 3:
        raise ValueError("expected at least three areas")

    source = str(metadata["source_file"])
    match = ACCOUNT_RE.search(source)
    if match is None:
        raise ValueError(f"no dotted control account in source_file: {source}")
    account_id = match.group()
    if output_name is None:
        output_name = f"sec-forms-{account_id}.tex"
    control_account = str(data["control_account"])
    title = re.sub(r"^\s*" + re.escape(account_id) + r"(?:\s*[-–:]\s*|\s+)", "", control_account)
    if title == control_account or not title.strip():
        raise ValueError(f"cannot extract title from control_account: {control_account}")
    pdf = f"{account_id}.pdf"
    scores = [data["score_overall"], *(area["score"] for area in areas[:3])]
    nodes = "\n".join(score_node(i, score) for i, score in enumerate(scores))
    # The PDF path is relative to the compiled Beamer document, as in the example.
    heading = tex(title)
    paragraphs = "\n".join(
        f"\\textbf{{\\(c_{i}\\) {tex(area['area_name'])}.}}\n"
        f"{tex(area.get('text', ''))}\\par\\vspace{{0.6em}}"
        for i, area in enumerate(areas[:3], 1)
    )
    return f'''% \\input{{\\pSections/"{output_name}"}}
\\typeout{{\\enumContent \\pSections/"{output_name}"}}

% Generated by: {Path(__file__).resolve()}
% Generated at: {datetime.datetime.now().astimezone().isoformat(timespec="seconds")}

\\begin{{frame}}{{\\href{{run:../local/source-docs/{pdf}}}{{{heading}}}}}
\\centering
\\makebox[\\textwidth][c]{{%
\\begin{{tikzpicture}}[
    x=1.7cm, y=0.48cm,
    every node/.style={{font=\\small, text height=1.7ex, text depth=.4ex}}
]
    \\node at (0,0) {{\\rd{{Low}}}};
    \\node at (1,0) {{Medium}};
    \\node at (2,0) {{\\bl{{Strong}}}};
    \\draw (-0.35,-0.5) -- (2.35,-0.5);
    \\foreach \\r in {{0,1,2,3}}
        \\node at (-0.65,-\\r-1) {{$c_{{\\r}}$}};
{nodes}
\\end{{tikzpicture}}}}
\\par
\\vspace{{0.75em}}
\\textbf{{\\small{{\\(c_0\\) Overall score}}}}\\\\\\par
\\vspace{{0.5em}}
\\begin{{minipage}}{{0.85\\textwidth}}
\\raggedright
\\fontsize{{7}}{{9}}\\selectfont
{overall_text(data.get('leadership_messages', ''))}\\par
\\end{{minipage}}
\\end{{frame}}
%
\\begin{{frame}}{{{heading}}}
\\begin{{minipage}}{{0.90\\textwidth}}
\\raggedright
\\fontsize{{8}}{{9.5}}\\selectfont
{paragraphs}
\\end{{minipage}}
\\end{{frame}}

\\endinput
'''


def print_provenance():
    print("\n=== BASIC PROVENANCE ===")
    print(f"Timestamp: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"User: {getpass.getuser()}")
    print(f"Script location: {Path(__file__).resolve()}")
    print(f"Working directory: {Path.cwd()}")
    print("\n=== SYSTEM ===")
    print(f"OS: {platform.system()} {platform.release()}")
    print(f"Machine: {platform.machine()}")
    print(f"Processor: {platform.processor()}")
    print("\n=== PYTHON ===")
    print(f"• Version: {platform.python_version()}")
    print(f"• Executable: {sys.executable}")
    print(f"• Implementation: {platform.python_implementation()}")


def main():
    files = sorted(path for path in INPUT.glob("*.json") if path.is_file())
    if not files:
        raise SystemExit(f"No JSON files found in {INPUT}")
    documents = []
    accounts = []
    errors = []
    for path in files:
        try:
            document = json.loads(path.read_text(encoding="utf-8"))
            source = str(document["metadata"]["source_file"])
            match = ACCOUNT_RE.search(source)
            if match is None:
                raise ValueError(f"No account number in source_file: {source}")
            documents.append((path, document))
            accounts.append(match.group())
        except (OSError, UnicodeError, json.JSONDecodeError, KeyError, TypeError, ValueError) as error:
            errors.append((path, error))
            print(f"Skipped {path.name}: {error}", file=sys.stderr)
    counts = Counter(accounts)
    outputs = []
    used_names = set()
    for (path, document), account in zip(documents, accounts):
        try:
            if counts[account] == 1:
                name = f"sec-forms-{account}.tex"
            else:
                # Two review groups can assess the same control account. Keep both.
                review = path.stem.split(account, 1)[0].rstrip("_ ").split("_")[-1]
                slug = re.sub(r"[^a-z0-9]+", "-", review.lower()).strip("-") or "review"
                suffix = hashlib.sha256(path.name.encode("utf-8")).hexdigest()[:8]
                name = f"sec-forms-{account}-{slug}-{suffix}.tex"
            if name in used_names:
                raise ValueError(f"Output filename collision: {name}")
            slides = make_slides(document, path, name)
            outputs.append((OUTPUT / name, slides, path))
            used_names.add(name)
        except (KeyError, TypeError, ValueError) as error:
            errors.append((path, error))
            print(f"Skipped {path.name}: {error}", file=sys.stderr)
    OUTPUT.mkdir(parents=True, exist_ok=True)
    written = []
    for destination, slides, path in outputs:
        try:
            destination.write_text(slides, encoding="utf-8")
            written.append(destination)
            print(f"Wrote: {destination}")
        except OSError as error:
            errors.append((path, error))
            print(f"Skipped {path.name}: {error}", file=sys.stderr)
    injector = OUTPUT / "sec-forms.tex"
    injector_text = (
        '% \\input{\\pSections/"sec-forms.tex"}\n'
        '\\typeout{\\enumContent \\pSections/"sec-forms.tex"}\n\n'
        f'% Generated by: {Path(__file__).resolve()}\n'
        f'% Generated at: {datetime.datetime.now().astimezone().isoformat(timespec="seconds")}\n\n'
        + "".join(
            f'\t\\input{{\\pSections/"{destination.name}"}}\n'
            for destination in written
        )
        + '\n\\endinput  %  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -\n'
    )
    injector.write_text(injector_text, encoding="utf-8")
    print(f"Wrote: {injector}")
    print(f"JSON files: {len(files)}; slides written: {len(written)}; skipped: {len(errors)}")
    print_provenance()


if __name__ == "__main__":
    main()
