#!/usr/bin/env python3
"""Generate Beamer score slides for the first two JSON files in scraped-json."""

import datetime
import getpass
import json
import platform
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent
INPUT = ROOT / "scraped-json"
OUTPUT = ROOT / "beamer-slides"
ACCOUNT_RE = re.compile(r"(?<!\d)\d+(?:\.\d+){2,}(?!\d)")
TEX_CHARS = {"\\": r"\textbackslash{}", "{": r"\{", "}": r"\}",
             "#": r"\#", "$": r"\$", "%": r"\%", "&": r"\&",
             "_": r"\_", "^": r"\textasciicircum{}", "~": r"\textasciitilde{}"}


def tex(value):
    """Normalize whitespace and escape TeX syntax without changing words."""
    value = " ".join(str(value or "").split())
    return "".join(TEX_CHARS.get(character, character) for character in value)


def overall_text(value):
    """Keep the original wording, starting numbered responses 2 and 3 anew."""
    parts = re.split(r"(?m)^\s*(?=[23]\.\s)", str(value or ""))
    return r"\par\vspace{0.5em}".join(tex(part) for part in parts if part.strip())


def score_node(row, score):
    positions = {-1: (0, r"\rd{$\blacktriangle$}"),
                  0: (1, r"$\blacktriangle$"),
                  1: (2, r"\bl{$\blacktriangle$}")}
    if score not in positions:
        raise ValueError(f"c{row}: unsupported score {score!r}; expected -1, 0, or 1")
    x, symbol = positions[score]
    return f"    \\node at ({x},-{row + 1}) {{{symbol}}};"


def make_slides(document, path):
    metadata = document["metadata"]
    data = document["data"]
    areas = data["areas"]
    if len(areas) < 3:
        raise ValueError("expected at least three areas")

    source = str(metadata["source_file"])
    match = ACCOUNT_RE.search(source)
    if match is None:
        raise ValueError(f"no dotted control account in source_file: {source}")
    account_id = match.group()
    control_account = str(data["control_account"])
    title = re.sub(r"^\s*" + re.escape(account_id) + r"(?:\s*[-–:]\s*|\s+)", "", control_account)
    if title == control_account or not title.strip():
        raise ValueError(f"cannot extract title from control_account: {control_account}")
    pdf = f"{account_id}.pdf"
    scores = [data["score_overall"], *(area["score"] for area in areas[:3])]
    nodes = "\n".join(score_node(i, score) for i, score in enumerate(scores))
    # The PDF path is relative to the compiled Beamer document, as in the example.
    heading = tex(title)
    paragraphs = "\n".join(
        f"\\textbf{{{tex(area['area_name'])} \\(c_{i}\\).}}\n"
        f"{tex(area.get('text', ''))}\\par\\vspace{{0.6em}}"
        for i, area in enumerate(areas[:3], 1)
    )
    return f'''% Generated by: {Path(__file__).resolve()}
% Generated at: {datetime.datetime.now().astimezone().isoformat(timespec="seconds")}
% \\input{{\\pSections/"sec-forms-{account_id}.tex"}}
\\typeout{{\\enumContent \\pSections/"sec-forms-{account_id}.tex"}}

\\begin{{frame}}{{\\href{{run:../local/source-docs/{pdf}}}{{{heading}}}}}
\\centering
\\makebox[\\textwidth][c]{{%
\\begin{{tikzpicture}}[
    x=1.7cm, y=0.48cm,
    every node/.style={{font=\\small, text height=1.7ex, text depth=.4ex}}
]
    \\node at (0,0) {{\\rd{{Low}}}};
    \\node at (1,0) {{Medium}};
    \\node at (2,0) {{\\bl{{Strong}}}};
    \\draw (-0.35,-0.5) -- (2.35,-0.5);
    \\foreach \\r in {{0,1,2,3}}
        \\node at (-0.65,-\\r-1) {{$c_{{\\r}}$}};
{nodes}
\\end{{tikzpicture}}}}
\\par
\\vspace{{0.75em}}
\\textbf{{\\small{{$c_{{0}}$ Overall score}}}}\\\\\\par
\\vspace{{0.5em}}
\\begin{{minipage}}{{0.85\\textwidth}}
\\raggedright
\\fontsize{{7}}{{9}}\\selectfont
{overall_text(data.get('leadership_messages', ''))}\\par
\\end{{minipage}}
\\end{{frame}}
%
\\begin{{frame}}{{{heading}}}
\\begin{{minipage}}{{0.90\\textwidth}}
\\raggedright
\\fontsize{{8}}{{9.5}}\\selectfont
{paragraphs}
\\end{{minipage}}
\\end{{frame}}

\\endinput
'''


def print_provenance():
    print("\n=== BASIC PROVENANCE ===")
    print(f"Timestamp: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"User: {getpass.getuser()}")
    print(f"Script location: {Path(__file__).resolve()}")
    print(f"Working directory: {Path.cwd()}")
    print("\n=== SYSTEM ===")
    print(f"OS: {platform.system()} {platform.release()}")
    print(f"Machine: {platform.machine()}")
    print(f"Processor: {platform.processor()}")
    print("\n=== PYTHON ===")
    print(f"• Version: {platform.python_version()}")
    print(f"• Executable: {sys.executable}")
    print(f"• Implementation: {platform.python_implementation()}")


def main():
    files = sorted(INPUT.glob("*.json"))[:2]
    if len(files) < 2:
        raise SystemExit(f"Expected at least two JSON files in {INPUT}")
    # Validate both before writing either file.
    outputs = []
    for path in files:
        document = json.loads(path.read_text(encoding="utf-8"))
        slides = make_slides(document, path)
        account = ACCOUNT_RE.search(str(document["metadata"]["source_file"])).group()
        outputs.append((OUTPUT / f"sec-forms-{account}.tex", slides))
    if outputs[0][0] == outputs[1][0]:
        raise SystemExit("The first two source documents have the same account ID")
    OUTPUT.mkdir(parents=True, exist_ok=True)
    for destination, slides in outputs:
        destination.write_text(slides, encoding="utf-8")
        print(f"Wrote: {destination}")
    injector = OUTPUT / "sec-forms.tex"
    injector_text = (
        f'% Generated by: {Path(__file__).resolve()}\n'
        f'% Generated at: {datetime.datetime.now().astimezone().isoformat(timespec="seconds")}\n'
        '% \\input{\\pSections/"sec-forms.tex"}\n'
        '\\typeout{\\enumContent \\pSections/"sec-forms.tex"}\n\n'
        + "".join(
            f'\t\\input{{\\pSections/"{destination.name}"}}\n'
            for destination, _ in outputs
        )
        + '\n\\endinput  %  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -\n'
    )
    injector.write_text(injector_text, encoding="utf-8")
    print(f"Wrote: {injector}")
    print_provenance()


if __name__ == "__main__":
    main()

#dantopa@isomer:~/repos-isomer/github/jop/python/bae/scores$ python3 json_to_beamer-3.py
#Wrote: /home/dantopa/repos-isomer/github/jop/python/bae/scores/beamer-slides/sec-forms-1.04.01.04.02.19.tex
#Wrote: /home/dantopa/repos-isomer/github/jop/python/bae/scores/beamer-slides/sec-forms-1.04.02.01.02.01.02.tex
#Wrote: /home/dantopa/repos-isomer/github/jop/python/bae/scores/beamer-slides/sec-forms.tex

#=== BASIC PROVENANCE ===
#Timestamp: 2026-09-27 11:51:44
#User: dantopa
#Script location: /home/dantopa/repos-isomer/github/jop/python/bae/scores/json_to_beamer-3.py
#Working directory: /home/dantopa/repos-isomer/github/jop/python/bae/scores

#=== SYSTEM ===
#OS: Linux 7.0.11-76070011-generic
#Machine: x86_64
#Processor:

#=== PYTHON ===
#• Version: 3.14.4
#• Executable: /usr/bin/python3
#• Implementation: CPython

# dantopa@isomer:~/repos-isomer/github/jop/python/bae/scores$ cp beamer-slides/sec-forms*.tex $pFramework/pres/zebra/sections/.

